### PR TITLE
Remove the dependency on tabbrowser.dtd

### LINKED ISSUE #99: FireGestures doesn't work on latest Firefox Nightly (at least in some configurations)
Today a commit landed on the main Firefox trunk that's caused FireGestures to stop working. I filed [Firefox bug #1189434](https://bugzilla.mozilla.org/show_bug.cgi?id=1189434) about it but the Firefox developers believe that the correct solution is for FireGestures to be updated (one developer has offered assistance with this, per the bug comments). Although it's not mentioned in my Firefox bugzilla report, this happens both with and without e10s on.

(It's possible that the specific commit my Firefox trunk bisection found is not actually the core problem, merely something that turns on the core problem in Firefox.)

When I look at the browser console (with e10s off), I see:

    TypeError: this._gestureMapping is null browser.js:103:8
    NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "this._gestureMapping is null" {file: "chrome://firegestures/content/browser.js" line: 103}]'[JavaScript Error: "this._gestureMapping is null" {file: "chrome://firegestures/content/browser.js" line: 103}]' when calling method: [xdIGestureObserver::onDirectionChanged] xdGestureHandler.js:413:0
    TypeError: this._getLocaleString is not a function browser.js:123:6
    NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "this._getLocaleString is not a function" {file: "chrome://firegestures/content/browser.js" line: 123}]'[JavaScript Error: "this._getLocaleString is not a function" {file: "chrome://firegestures/content/browser.js" line: 123}]' when calling method: [xdIGestureObserver::onMouseGesture] xdGestureHandler.js:447:0

I don't seem to see this in my non-e10s Firefox Nightly from my most recent working build.

(This change is so new that it's not in the overnight Nightly builds, so a prebuilt Firefox Nightly with it in will only become available tomorrow, July 31st. I guess I was 'lucky' to be rebuilding my Nightly build today, since I don't do it every day.)

### PR DESCRIPTION
**Pull request by ehsan**
This should fix #99.

### CODE REVIEW

**Comment by ehsan** [comment]
Note that `&closeTab.label;` which is used in this file is also available from browser.dtd.

**Comment by toyotabedzrock** [comment]
I can confirm this fixes the problem for the single process nightly branch.

**Comment by mpopp75** [comment]
I tried your fixed version and it works fine except that the "open in new tab" gesture doesn't work.

Does this perhaps require tabbrowser.dtd?

**Comment by toyotabedzrock** [comment]
@mpopp75 That gesture works for me. When you edited the extension did you increment the version number and remove the meta directory?

**Comment by mpopp75** [comment]
I did this: got a clone of https://github.com/ehsan/firegestures.git, switched to branch 99, incremented the version number in install.rdf to 1.11a1 and created a zip file which I renamed to firegestures.xpi. This I installed. I don't see any meta (or META-INF) directory.

I used my default Firefox profile to test it which has a number of other addons installed. I can't rule out that some other addon breaks this newly fixed version, but it definitely worked with the same addons before Firegestures broke in Nightly.

**Comment by ehsan** [comment]
I don't really understand how removing tabbrowser.dtd could have changed anything with regards to opening a link in a new tab, sorry.  This extension doesn't reference that file any more, so I don't think that is related to this issue.

**Comment by mpopp75** [comment]
Interestingly, with Firefox 40.0 (probably earlier versions too) the open a link in a new tab gesture works fine.

As of today's Nightly, unverified addons no longer work. Since this fixed version definitely solves the majority of problems and doesn't seem to break anything that wasn't broken (i.e. the addon being broken with e10s which this is all about), I would recommend releasing this fixed version (also to get it verified by Mozilla). If any problems remain, it's easier to tackle them from there.

**Comment by toyotabedzrock** [comment]
@mpopp75  In about:config change "xpinstall.signatures.required" to false. The meta-inf is only in the official 1.10 download on the Mozilla addons site. You should download that and modify it.

**Comment by mpopp75** [comment]
Even with "xpinstall.signatures.required" set to false I can't install the updated version, at least for now. Since the verification stuff in Firefox is very new, maybe there are still some flaws which need fixing.

**Comment by mpopp75** [comment]
"xpinstall.signatures.required" works now and I tried the modified addon with default settings in a fresh & up-to-date Nightly profile. However the "open link in a new tab" gesture still doesn't work.

But I noticed a message saying: Starting point of gesture is not on a link. Even though it certainly was. Maybe there is some other issue with that.

It could also have to do with me using the Linux64 version of Firefox (Xubuntu 15.04, 64bit), in case there is some platform dependent problem.

**Comment by gomita** [comment]
Thanks, eshan.
I have merged your pull request.

**Pull request merged**
